In [42]:
# import numpy
# create array x
import numpy as np
x = np.array([ [1,2,3,4], [1,2,3,4], [1,9,8,7]])

In [43]:
# print the shape of x
print x.shape

(3, 4)


In [33]:
# create a two dimensional array
y= np.array([[1,2],[3,4]])

In [34]:
# print shape of 2d array
print y.shape

(2, 2)


In [45]:
# reshape the array to 2 x 6
q = np.reshape(x,(2,6))
q

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 9, 8, 7]])

In [47]:
# reshape the array to 1 x 12
r = np.reshape(x,(1,12))
r

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 9, 8, 7]])

In [53]:
# transpose the array
s = r.T
s

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [3],
       [4],
       [1],
       [9],
       [8],
       [7]])

In [49]:
# indexing method 1
print q[0]
print q[0,1]

[1 2 3 4 1 2]
2


In [50]:
# indexing method 2
q[0][1]

2

In [13]:
# indexing method 3
q[0]

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6