In [124]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [125]:
a

array([1, 2, 3, 4, 5])

In [126]:
reshaped_a = a.reshape(1,-1)

In [127]:
reshaped_a

array([[1, 2, 3, 4, 5]])

In [128]:
reshaped_a.ndim

2

In [129]:
reshaped_a.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [130]:
reshaped_a.T.shape

(5, 1)

In [131]:
x = np.array([1,2,3,4,5])
y = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [132]:
x.reshape(5,1).reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [133]:
type(x)

numpy.ndarray

In [134]:
x

array([1, 2, 3, 4, 5])

In [135]:
a.dtype

dtype('int64')

In [46]:
zf = np.array([1,2,3,4,'5.0'])

In [47]:
zf.dtype

dtype('S21')

In [15]:
b

array([5, 4, 3, 2, 1])

In [50]:
np.add(a, b)

array([6, 6, 6, 6, 6])

In [51]:
np.subtract(a, b)

array([-4, -2,  0,  2,  4])

In [52]:
np.dot(a, b)

35

In [136]:
list_one = np.array([1, 3, 5, 7, 9])
list_two = np.array([2, 4, 6, 8, 10])

In [137]:
np.dot(list_one,list_two)

190

In [149]:
list_one = np.array([1, 3, 5, 7, 9])
list_two = np.array([2, 4, 6, 8, 10])

In [146]:
def dotProd(x,y):
    total = 0
    for i in range(len(x)):
        total= total+x[i]*y[i]
    return total
    
dotProd(list_one,list_two)

190

In [150]:
def dotProd(x,y):
    total = 0
    total = [total + (i*j) for i, j in zip(x,y)]

    print sum(total)
    
dotProd(list_one,list_two)

TypeError: 'int' object is not callable

In [151]:
sum([x*y for x,y in zip(list_one, list_two)])


TypeError: 'int' object is not callable